In [296]:
%%capture
!pip install otter-grader

files = "https://github.com/mateuszwyszynski/python_basics/raw/main/week_8/tests.zip"
!wget -O ./tests.zip $files && unzip -o tests.zip

import otter
grader = otter.Notebook(colab = True)
!git clone https://github.com/mateuszwyszynski/python_basics.git

# Powt√≥rka

In [297]:
import pandas as pd

In [298]:
moj_df = pd.read_excel('zubelki.xlsx') # zmien nazwe pliku na swoja! wystarczy jedynie pd.read_excel('nazwapliku.xlsx')

In [299]:
moj_df

,Country,obesity,Intentional homicides,"Lifetime, death (%)",Life expectancy,Death rate,GDP,Agriculture,Net income,Access to electricity,...,A woman in industrial,A woman night,A woman a job in man,A woman can trave,A woman a business,A woman a bank account,A woman rights,Expected schooling,"Unemployment with education,",Share of youth not in education
0,Argentina,29.0,NaN,0.095583,79.583,7.626,5.248197e+11,2.381568e+10,4.368233e+11,99.989578,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,21.085939,3.340000,7.060000
1,Australia,28.4,0.656959,0.012335,84.600,6.600,1.428530e+12,3.511046e+10,1.103232e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.389780,NaN,NaN
2,Austria,18.3,0.717616,0.007393,84.100,9.200,1.916934e+12,8.473612e+10,1.416962e+12,99.699997,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,18.930410,4.200000,22.490000
3,Belgium,21.0,NaN,0.009536,84.000,9.500,1.389482e+13,9.786148e+11,1.036587e+13,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,15.663290,2.820000,NaN
4,Belarus,26.3,2.099139,0.004469,79.000,12.600,2.790957e+12,4.601944e+10,2.346609e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.550501,3.330000,8.930000
5,Brazil,25.4,4.053943,0.111558,78.934,6.311,3.977289e+12,2.740405e+10,3.382188e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.078091,7.920000,30.100000
6,Canada,29.3,0.828751,0.016605,84.000,7.400,2.701112e+12,4.313718e+11,2.359160e+12,95.699997,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,14.399920,4.460000,12.270000
7,Bulgaria,24.3,0.598682,0.014929,78.500,15.100,2.091932e+12,4.069687e+10,1.745055e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.722601,NaN,NaN
8,Chile,31.0,0.961061,0.023302,82.293,5.993,5.036892e+12,5.272081e+10,3.936382e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.832951,7.340000,18.920000
9,Colombia,26.6,4.226919,0.162510,79.523,5.453,1.222408e+12,4.136385e+10,9.488131e+11,99.500000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN
10,China,6.5,NaN,0.048028,78.574,7.040,9.140434e+11,1.508787e+10,7.706273e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,14.668490,12.950000,31.070000
11,Croatia,24.5,0.915552,0.009778,81.300,12.300,1.657329e+12,5.625397e+10,1.274722e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.924050,6.490000,13.990000
12,Czech Republic,25.4,0.666688,0.006028,82.100,10.200,7.865218e+11,1.749576e+10,6.370044e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.750549,1.430000,7.800000
13,Cyprus,21.6,0.855931,0.009355,82.671,6.890,1.420994e+12,3.918525e+10,1.205678e+12,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,19.437679,7.980000,11.690000
14,Denmark,17.0,0.801130,0.006749,82.800,9.200,7.355393e+11,4.670854e+09,5.434200e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.434000,4.710000,7.600000
15,"Egypt, Arab Rep.",41.1,NaN,0.142538,73.766,5.915,7.784719e+11,4.496463e+10,6.574194e+11,100.000000,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,13.620190,34.759998,36.599998
16,Estonia,21.8,1.286889,0.017563,82.200,11.700,2.900791e+12,1.672666e+10,2.408966e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.719540,3.420000,8.860000
17,Finland,20.6,0.788341,0.005531,84.400,9.800,2.061186e+13,1.897446e+11,1.758172e+13,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.088640,4.230000,8.370000
18,France,21.1,1.028481,0.014834,85.800,8.900,5.432738e+11,3.276322e+09,4.462278e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.303471,5.430000,10.380000
19,Georgia,23.8,1.620563,0.053827,77.621,12.992,6.003126e+10,3.956125e+09,4.856248e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.908739,11.390000,30.990000
20,Greece,25.4,0.481106,0.003933,84.000,11.000,6.636342e+10,2.246147e+09,5.448209e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.530480,1.930000,6.470000
21,Germany,20.4,1.123905,0.007432,83.500,11.100,1.725329e+12,2.932873e+10,1.397376e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,19.458490,18.400000,14.010000
22,Hungary,24.6,1.602628,0.016274,79.700,13.000,2.975717e+11,1.055089e+10,2.277557e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.212420,1.700000,5.320000
23,Iceland,19.4,0.603992,0.008099,84.100,6.900,3.341982e+11,2.080621e+10,2.736790e+11,98.500000,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,15.420670,24.690001,48.250000
24,Ireland,25.5,0.084343,0.011353,83.600,6.400,2.489501e+11,4.821279e+09,1.854725e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.710000,14.020000
25,India,5.1,2.833142,0.364670,70.142,7.195,6.224787e+10,1.840727e+09,5.180870e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.479420,3.870000,9.890000
26,Israel,26.2,0.563076,0.010854,84.200,5.200,2.552267e+10,4.424457e+08,2.156272e+10,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,16.731119,2.650000,15.000000
27,Italy,19.5,0.477460,0.002177,85.600,10.100,3.568412e+11,3.663223e+09,3.059681e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,20.231270,7.020000,19.360001
28,Japan,3.7,0.301478,0.006099,87.140,10.500,2.497130e+11,2.803028e+10,2.165320e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,15.161000,2.510000,3.540000
29,"Korea, Dem. People's Rep.",7.3,NaN,0.162713,75.119,8.856,3.048950e+10,6.771747e+08,2.523230e+10,100.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Lithuania,27.8,2.953250,0.013467,80.100,14.300,2.757151e+11,6.580279e+09,2.253553e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17.027361,2.690000,7.610000
31,Malta,28.5,0.918864,0.009547,84.400,7.300,1.759970e+10,1.190127e+09,1.440067e+10,99.900002,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,17.051001,2.090000,7.760000
32,Mexico,32.8,4.477110,0.079425,77.826,5.851,2.120494e+11,7.708864e+09,1.769715e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.158890,4.390000,28.610001
33,Netherlands,20.0,0.351440,0.009194,83.200,8.700,1.605868e+11,5.597915e+09,1.285686e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,13.289240,NaN,NaN
34,New Zealand,31.4,0.928956,0.018237,83.400,6.610,2.626706e+10,1.030398e+09,2.057732e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,18.848000,2.490000,4.150000
35,Norway,22.5,0.422315,0.004420,84.200,7.800,3.850417e+11,3.421852e+09,2.054275e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,19.882839,2.300000,12.750000
36,Portugal,21.2,NaN,0.010470,84.300,10.700,3.736412e+11,4.450253e+09,3.236846e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,18.819040,2.140000,4.570000
37,Poland,22.2,0.362745,0.003477,82.000,10.200,NaN,NaN,NaN,47.630955,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.796410,1.970000,10.100000
38,Russian Federation,26.9,5.326215,0.032981,77.060,12.900,5.375091e+10,1.547827e+09,4.535771e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.758619,5.530000,8.390000
39,Singapore,6.3,0.259759,0.010204,85.100,4.800,1.486471e+10,1.111946e+08,NaN,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,15.921450,4.810000,NaN
40,South Africa,39.6,NaN,0.313375,66.654,9.599,1.180962e+11,1.442750e+10,1.015128e+11,98.099998,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.729259,NaN,5.600000
41,Spain,22.8,0.475864,0.004869,86.300,8.800,2.122257e+11,1.199578e+10,1.725410e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,13.867560,13.170000,34.150002
42,Sweden,18.1,0.589786,0.008172,84.100,9.200,4.369997e+11,8.141285e+09,3.503814e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,18.209591,10.150000,11.860000
43,Switzerland,16.9,0.591043,0.008183,85.600,7.800,2.423131e+11,4.934779e+09,1.936451e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,4.260000,4.750000
44,Thailand,12.7,NaN,0.052834,80.189,7.467,5.874117e+11,1.373619e+10,4.949025e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,16.311640,3.180000,5.890000
45,Turkey,39.2,1.081064,0.038059,79.816,5.390,3.759815e+11,1.135824e+08,2.730617e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.705629,1.700000,18.920000
46,Ukraine,25.7,NaN,0.028803,76.460,14.700,5.554554e+11,7.736308e+09,4.704748e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,17.613480,16.799999,33.470001
47,United States,37.0,2.277249,0.034195,81.100,8.493,5.066111e+11,4.145954e+10,3.880200e+11,99.820000,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,NaN,6.810000,NaN
48,United Kingdom,28.6,0.867361,0.013099,83.000,9.100,1.308910e+11,1.327174e+10,1.154703e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17.737129,2.490000,11.220000
49,Morocco,32.2,0.592692,0.185406,77.202,5.093,4.048421e+11,9.211179e+09,3.316214e+11,84.699997,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.909849,2.480000,11.540000

In [300]:
moj_df.columns

Index(['Country', 'obesity', 'Intentional homicides', 'Lifetime, death (%)',
       'Life expectancy', 'Death rate', 'GDP', 'Agriculture', 'Net income',
       'Access to electricity', 'A woman in ob dangerous',
       'A woman in industrial', 'A woman  night', 'A woman a job in man',
       'A woman can trave', 'A woman a business', 'A woman  a bank account',
       'A woman rights', 'Expected  schooling', 'Unemployment with education,',
       'Share of youth not in education'],
      dtype='object')

In [301]:
liczba_wierszy = moj_df.shape[0] 
liczba_kolumn = moj_df.shape[1]

print('liczba wierszy: ', liczba_wierszy,', liczba kolumn: ', liczba_kolumn)

liczba wierszy:  50 , liczba kolumn:  21

In [302]:
moj_df.dtypes

Country                             object
obesity                            float64
Intentional homicides              float64
Lifetime, death (%)                float64
Life expectancy                    float64
Death rate                         float64
GDP                                float64
Agriculture                        float64
Net income                         float64
Access to electricity              float64
A woman in ob dangerous            float64
A woman in industrial              float64
A woman  night                     float64
A woman a job in man               float64
A woman can trave                  float64
A woman a business                 float64
A woman  a bank account            float64
A woman rights                     float64
Expected  schooling                float64
Unemployment with education,       float64
Share of youth not in education    float64
dtype: object

In [303]:

#moj_df['nazwa_kolumny'] = moj_df['nazwa_kolumny'].astype('float64') # zastap 'nazwa_kolumny' wybrana przez siebie kolumna

In [304]:
moj_df[moj_df.isna().any(axis=1)]

,Country,obesity,Intentional homicides,"Lifetime, death (%)",Life expectancy,Death rate,GDP,Agriculture,Net income,Access to electricity,...,A woman in industrial,A woman night,A woman a job in man,A woman can trave,A woman a business,A woman a bank account,A woman rights,Expected schooling,"Unemployment with education,",Share of youth not in education
0,Argentina,29.0,NaN,0.095583,79.583,7.626,5.248197e+11,2.381568e+10,4.368233e+11,99.989578,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,21.085939,3.340000,7.060000
1,Australia,28.4,0.656959,0.012335,84.600,6.600,1.428530e+12,3.511046e+10,1.103232e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.389780,NaN,NaN
3,Belgium,21.0,NaN,0.009536,84.000,9.500,1.389482e+13,9.786148e+11,1.036587e+13,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,15.663290,2.820000,NaN
7,Bulgaria,24.3,0.598682,0.014929,78.500,15.100,2.091932e+12,4.069687e+10,1.745055e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.722601,NaN,NaN
9,Colombia,26.6,4.226919,0.162510,79.523,5.453,1.222408e+12,4.136385e+10,9.488131e+11,99.500000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN
10,China,6.5,NaN,0.048028,78.574,7.040,9.140434e+11,1.508787e+10,7.706273e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,14.668490,12.950000,31.070000
15,"Egypt, Arab Rep.",41.1,NaN,0.142538,73.766,5.915,7.784719e+11,4.496463e+10,6.574194e+11,100.000000,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,13.620190,34.759998,36.599998
24,Ireland,25.5,0.084343,0.011353,83.600,6.400,2.489501e+11,4.821279e+09,1.854725e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.710000,14.020000
29,"Korea, Dem. People's Rep.",7.3,NaN,0.162713,75.119,8.856,3.048950e+10,6.771747e+08,2.523230e+10,100.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Netherlands,20.0,0.351440,0.009194,83.200,8.700,1.605868e+11,5.597915e+09,1.285686e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,13.289240,NaN,NaN
36,Portugal,21.2,NaN,0.010470,84.300,10.700,3.736412e+11,4.450253e+09,3.236846e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,18.819040,2.140000,4.570000
37,Poland,22.2,0.362745,0.003477,82.000,10.200,NaN,NaN,NaN,47.630955,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.796410,1.970000,10.100000
39,Singapore,6.3,0.259759,0.010204,85.100,4.800,1.486471e+10,1.111946e+08,NaN,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,15.921450,4.810000,NaN
40,South Africa,39.6,NaN,0.313375,66.654,9.599,1.180962e+11,1.442750e+10,1.015128e+11,98.099998,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.729259,NaN,5.600000
43,Switzerland,16.9,0.591043,0.008183,85.600,7.800,2.423131e+11,4.934779e+09,1.936451e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,4.260000,4.750000
44,Thailand,12.7,NaN,0.052834,80.189,7.467,5.874117e+11,1.373619e+10,4.949025e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,16.311640,3.180000,5.890000
46,Ukraine,25.7,NaN,0.028803,76.460,14.700,5.554554e+11,7.736308e+09,4.704748e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,17.613480,16.799999,33.470001
47,United States,37.0,2.277249,0.034195,81.100,8.493,5.066111e+11,4.145954e+10,3.880200e+11,99.820000,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,NaN,6.810000,NaN

In [305]:
#moj_df = moj_df.dropna() # uzyj tej linijki, jesli chcesz wyrzucic panstwa, w ktorych wystepuja NA
moj_df = moj_df.fillna(0) # lub tej, jesli chcesz je zamienic na 0

moj_df

,Country,obesity,Intentional homicides,"Lifetime, death (%)",Life expectancy,Death rate,GDP,Agriculture,Net income,Access to electricity,...,A woman in industrial,A woman night,A woman a job in man,A woman can trave,A woman a business,A woman a bank account,A woman rights,Expected schooling,"Unemployment with education,",Share of youth not in education
0,Argentina,29.0,0.000000,0.095583,79.583,7.626,5.248197e+11,2.381568e+10,4.368233e+11,99.989578,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,21.085939,3.340000,7.060000
1,Australia,28.4,0.656959,0.012335,84.600,6.600,1.428530e+12,3.511046e+10,1.103232e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.389780,0.000000,0.000000
2,Austria,18.3,0.717616,0.007393,84.100,9.200,1.916934e+12,8.473612e+10,1.416962e+12,99.699997,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,18.930410,4.200000,22.490000
3,Belgium,21.0,0.000000,0.009536,84.000,9.500,1.389482e+13,9.786148e+11,1.036587e+13,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,15.663290,2.820000,0.000000
4,Belarus,26.3,2.099139,0.004469,79.000,12.600,2.790957e+12,4.601944e+10,2.346609e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.550501,3.330000,8.930000
5,Brazil,25.4,4.053943,0.111558,78.934,6.311,3.977289e+12,2.740405e+10,3.382188e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.078091,7.920000,30.100000
6,Canada,29.3,0.828751,0.016605,84.000,7.400,2.701112e+12,4.313718e+11,2.359160e+12,95.699997,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,14.399920,4.460000,12.270000
7,Bulgaria,24.3,0.598682,0.014929,78.500,15.100,2.091932e+12,4.069687e+10,1.745055e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.722601,0.000000,0.000000
8,Chile,31.0,0.961061,0.023302,82.293,5.993,5.036892e+12,5.272081e+10,3.936382e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.832951,7.340000,18.920000
9,Colombia,26.6,4.226919,0.162510,79.523,5.453,1.222408e+12,4.136385e+10,9.488131e+11,99.500000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000
10,China,6.5,0.000000,0.048028,78.574,7.040,9.140434e+11,1.508787e+10,7.706273e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,14.668490,12.950000,31.070000
11,Croatia,24.5,0.915552,0.009778,81.300,12.300,1.657329e+12,5.625397e+10,1.274722e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.924050,6.490000,13.990000
12,Czech Republic,25.4,0.666688,0.006028,82.100,10.200,7.865218e+11,1.749576e+10,6.370044e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.750549,1.430000,7.800000
13,Cyprus,21.6,0.855931,0.009355,82.671,6.890,1.420994e+12,3.918525e+10,1.205678e+12,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,19.437679,7.980000,11.690000
14,Denmark,17.0,0.801130,0.006749,82.800,9.200,7.355393e+11,4.670854e+09,5.434200e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.434000,4.710000,7.600000
15,"Egypt, Arab Rep.",41.1,0.000000,0.142538,73.766,5.915,7.784719e+11,4.496463e+10,6.574194e+11,100.000000,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,13.620190,34.759998,36.599998
16,Estonia,21.8,1.286889,0.017563,82.200,11.700,2.900791e+12,1.672666e+10,2.408966e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.719540,3.420000,8.860000
17,Finland,20.6,0.788341,0.005531,84.400,9.800,2.061186e+13,1.897446e+11,1.758172e+13,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.088640,4.230000,8.370000
18,France,21.1,1.028481,0.014834,85.800,8.900,5.432738e+11,3.276322e+09,4.462278e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.303471,5.430000,10.380000
19,Georgia,23.8,1.620563,0.053827,77.621,12.992,6.003126e+10,3.956125e+09,4.856248e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.908739,11.390000,30.990000
20,Greece,25.4,0.481106,0.003933,84.000,11.000,6.636342e+10,2.246147e+09,5.448209e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.530480,1.930000,6.470000
21,Germany,20.4,1.123905,0.007432,83.500,11.100,1.725329e+12,2.932873e+10,1.397376e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,19.458490,18.400000,14.010000
22,Hungary,24.6,1.602628,0.016274,79.700,13.000,2.975717e+11,1.055089e+10,2.277557e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.212420,1.700000,5.320000
23,Iceland,19.4,0.603992,0.008099,84.100,6.900,3.341982e+11,2.080621e+10,2.736790e+11,98.500000,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,15.420670,24.690001,48.250000
24,Ireland,25.5,0.084343,0.011353,83.600,6.400,2.489501e+11,4.821279e+09,1.854725e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,1.710000,14.020000
25,India,5.1,2.833142,0.364670,70.142,7.195,6.224787e+10,1.840727e+09,5.180870e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.479420,3.870000,9.890000
26,Israel,26.2,0.563076,0.010854,84.200,5.200,2.552267e+10,4.424457e+08,2.156272e+10,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,16.731119,2.650000,15.000000
27,Italy,19.5,0.477460,0.002177,85.600,10.100,3.568412e+11,3.663223e+09,3.059681e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,20.231270,7.020000,19.360001
28,Japan,3.7,0.301478,0.006099,87.140,10.500,2.497130e+11,2.803028e+10,2.165320e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,15.161000,2.510000,3.540000
29,"Korea, Dem. People's Rep.",7.3,0.000000,0.162713,75.119,8.856,3.048950e+10,6.771747e+08,2.523230e+10,100.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
30,Lithuania,27.8,2.953250,0.013467,80.100,14.300,2.757151e+11,6.580279e+09,2.253553e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17.027361,2.690000,7.610000
31,Malta,28.5,0.918864,0.009547,84.400,7.300,1.759970e+10,1.190127e+09,1.440067e+10,99.900002,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,17.051001,2.090000,7.760000
32,Mexico,32.8,4.477110,0.079425,77.826,5.851,2.120494e+11,7.708864e+09,1.769715e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.158890,4.390000,28.610001
33,Netherlands,20.0,0.351440,0.009194,83.200,8.700,1.605868e+11,5.597915e+09,1.285686e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,13.289240,0.000000,0.000000
34,New Zealand,31.4,0.928956,0.018237,83.400,6.610,2.626706e+10,1.030398e+09,2.057732e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,18.848000,2.490000,4.150000
35,Norway,22.5,0.422315,0.004420,84.200,7.800,3.850417e+11,3.421852e+09,2.054275e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,19.882839,2.300000,12.750000
36,Portugal,21.2,0.000000,0.010470,84.300,10.700,3.736412e+11,4.450253e+09,3.236846e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,18.819040,2.140000,4.570000
37,Poland,22.2,0.362745,0.003477,82.000,10.200,0.000000e+00,0.000000e+00,0.000000e+00,47.630955,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.796410,1.970000,10.100000
38,Russian Federation,26.9,5.326215,0.032981,77.060,12.900,5.375091e+10,1.547827e+09,4.535771e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.758619,5.530000,8.390000
39,Singapore,6.3,0.259759,0.010204,85.100,4.800,1.486471e+10,1.111946e+08,0.000000e+00,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,15.921450,4.810000,0.000000
40,South Africa,39.6,0.000000,0.313375,66.654,9.599,1.180962e+11,1.442750e+10,1.015128e+11,98.099998,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.729259,0.000000,5.600000
41,Spain,22.8,0.475864,0.004869,86.300,8.800,2.122257e+11,1.199578e+10,1.725410e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,13.867560,13.170000,34.150002
42,Sweden,18.1,0.589786,0.008172,84.100,9.200,4.369997e+11,8.141285e+09,3.503814e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,18.209591,10.150000,11.860000
43,Switzerland,16.9,0.591043,0.008183,85.600,7.800,2.423131e+11,4.934779e+09,1.936451e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,4.260000,4.750000
44,Thailand,12.7,0.000000,0.052834,80.189,7.467,5.874117e+11,1.373619e+10,4.949025e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,16.311640,3.180000,5.890000
45,Turkey,39.2,1.081064,0.038059,79.816,5.390,3.759815e+11,1.135824e+08,2.730617e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.705629,1.700000,18.920000
46,Ukraine,25.7,0.000000,0.028803,76.460,14.700,5.554554e+11,7.736308e+09,4.704748e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,17.613480,16.799999,33.470001
47,United States,37.0,2.277249,0.034195,81.100,8.493,5.066111e+11,4.145954e+10,3.880200e+11,99.820000,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.000000,6.810000,0.000000
48,United Kingdom,28.6,0.867361,0.013099,83.000,9.100,1.308910e+11,1.327174e+10,1.154703e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17.737129,2.490000,11.220000
49,Morocco,32.2,0.592692,0.185406,77.202,5.093,4.048421e+11,9.211179e+09,3.316214e+11,84.699997,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.909849,2.480000,11.540000

In [306]:
moj_df['A woman can trave'].unique() # zastap 'nazwa_kolumny' wybrana przez siebie kolumna

array([1., 0.])

In [307]:
# zastap 'nazwa_kolumny' wybrana przez siebie kolumna, natomiast 'napis1' oraz 'napis2' obecnymi napisami w swojej kolumnie (przed modyfikacja)
 #moj_df['A woman can trave'][moj_df['A woman can trave'] == ''] = 0
 #moj_df['nazwa_kolumny'][moj_df['nazwa_kolumny'] == 'napis2'] = 1
 #moj_df['nazwa_kolumny'] = moj_df['nazwa_kolumny'].astype('int') # zmiana typu na calkowitoliczbowy

In [308]:
moj_df.describe()

,obesity,Intentional homicides,"Lifetime, death (%)",Life expectancy,Death rate,GDP,Agriculture,Net income,Access to electricity,A woman in ob dangerous,A woman in industrial,A woman night,A woman a job in man,A woman can trave,A woman a business,A woman a bank account,A woman rights,Expected schooling,"Unemployment with education,",Share of youth not in education
count,50.000000,50.000000,50.000000,50.000000,50.000000,5.000000e+01,5.000000e+01,5.000000e+01,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,23.450000,1.053070,0.044889,81.297460,8.915480,1.489642e+12,4.824579e+10,1.208146e+12,98.470810,0.800000,0.680000,0.920000,0.960000,0.960000,0.980000,0.980000,0.840000,15.387414,5.602600,12.486400
std,8.356013,1.242252,0.075939,4.085078,2.674831,3.489336e+12,1.494237e+11,2.868869e+12,7.672398,0.404061,0.471212,0.274048,0.197949,0.197949,0.141421,0.141421,0.370328,5.516784,6.543538,11.221961
min,3.700000,0.000000,0.002177,66.654000,4.800000,0.000000e+00,0.000000e+00,0.000000e+00,47.630955,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.100000,0.354266,0.008117,79.130750,6.892500,1.734525e+11,3.736448e+09,1.395617e+11,100.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,15.424002,2.102500,5.390000
50%,24.400000,0.661823,0.012717,82.482000,8.828000,3.949419e+11,1.127334e+10,3.276530e+11,100.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,16.725930,3.380000,9.410000
75%,28.250000,1.067918,0.037093,84.100000,10.425000,1.371348e+12,3.366502e+10,1.064628e+12,100.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,18.091475,6.730000,14.755000
max,41.100000,5.326215,0.364670,87.140000,15.100000,2.061186e+13,9.786148e+11,1.758172e+13,100.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,21.085939,34.759998,48.250000

In [309]:
moj_df

,Country,obesity,Intentional homicides,"Lifetime, death (%)",Life expectancy,Death rate,GDP,Agriculture,Net income,Access to electricity,...,A woman in industrial,A woman night,A woman a job in man,A woman can trave,A woman a business,A woman a bank account,A woman rights,Expected schooling,"Unemployment with education,",Share of youth not in education
0,Argentina,29.0,0.000000,0.095583,79.583,7.626,5.248197e+11,2.381568e+10,4.368233e+11,99.989578,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,21.085939,3.340000,7.060000
1,Australia,28.4,0.656959,0.012335,84.600,6.600,1.428530e+12,3.511046e+10,1.103232e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.389780,0.000000,0.000000
2,Austria,18.3,0.717616,0.007393,84.100,9.200,1.916934e+12,8.473612e+10,1.416962e+12,99.699997,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,18.930410,4.200000,22.490000
3,Belgium,21.0,0.000000,0.009536,84.000,9.500,1.389482e+13,9.786148e+11,1.036587e+13,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,15.663290,2.820000,0.000000
4,Belarus,26.3,2.099139,0.004469,79.000,12.600,2.790957e+12,4.601944e+10,2.346609e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.550501,3.330000,8.930000
5,Brazil,25.4,4.053943,0.111558,78.934,6.311,3.977289e+12,2.740405e+10,3.382188e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.078091,7.920000,30.100000
6,Canada,29.3,0.828751,0.016605,84.000,7.400,2.701112e+12,4.313718e+11,2.359160e+12,95.699997,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,14.399920,4.460000,12.270000
7,Bulgaria,24.3,0.598682,0.014929,78.500,15.100,2.091932e+12,4.069687e+10,1.745055e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.722601,0.000000,0.000000
8,Chile,31.0,0.961061,0.023302,82.293,5.993,5.036892e+12,5.272081e+10,3.936382e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.832951,7.340000,18.920000
9,Colombia,26.6,4.226919,0.162510,79.523,5.453,1.222408e+12,4.136385e+10,9.488131e+11,99.500000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000
10,China,6.5,0.000000,0.048028,78.574,7.040,9.140434e+11,1.508787e+10,7.706273e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,14.668490,12.950000,31.070000
11,Croatia,24.5,0.915552,0.009778,81.300,12.300,1.657329e+12,5.625397e+10,1.274722e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.924050,6.490000,13.990000
12,Czech Republic,25.4,0.666688,0.006028,82.100,10.200,7.865218e+11,1.749576e+10,6.370044e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.750549,1.430000,7.800000
13,Cyprus,21.6,0.855931,0.009355,82.671,6.890,1.420994e+12,3.918525e+10,1.205678e+12,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,19.437679,7.980000,11.690000
14,Denmark,17.0,0.801130,0.006749,82.800,9.200,7.355393e+11,4.670854e+09,5.434200e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.434000,4.710000,7.600000
15,"Egypt, Arab Rep.",41.1,0.000000,0.142538,73.766,5.915,7.784719e+11,4.496463e+10,6.574194e+11,100.000000,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,13.620190,34.759998,36.599998
16,Estonia,21.8,1.286889,0.017563,82.200,11.700,2.900791e+12,1.672666e+10,2.408966e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.719540,3.420000,8.860000
17,Finland,20.6,0.788341,0.005531,84.400,9.800,2.061186e+13,1.897446e+11,1.758172e+13,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.088640,4.230000,8.370000
18,France,21.1,1.028481,0.014834,85.800,8.900,5.432738e+11,3.276322e+09,4.462278e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.303471,5.430000,10.380000
19,Georgia,23.8,1.620563,0.053827,77.621,12.992,6.003126e+10,3.956125e+09,4.856248e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.908739,11.390000,30.990000
20,Greece,25.4,0.481106,0.003933,84.000,11.000,6.636342e+10,2.246147e+09,5.448209e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.530480,1.930000,6.470000
21,Germany,20.4,1.123905,0.007432,83.500,11.100,1.725329e+12,2.932873e+10,1.397376e+12,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,19.458490,18.400000,14.010000
22,Hungary,24.6,1.602628,0.016274,79.700,13.000,2.975717e+11,1.055089e+10,2.277557e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.212420,1.700000,5.320000
23,Iceland,19.4,0.603992,0.008099,84.100,6.900,3.341982e+11,2.080621e+10,2.736790e+11,98.500000,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,15.420670,24.690001,48.250000
24,Ireland,25.5,0.084343,0.011353,83.600,6.400,2.489501e+11,4.821279e+09,1.854725e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,1.710000,14.020000
25,India,5.1,2.833142,0.364670,70.142,7.195,6.224787e+10,1.840727e+09,5.180870e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.479420,3.870000,9.890000
26,Israel,26.2,0.563076,0.010854,84.200,5.200,2.552267e+10,4.424457e+08,2.156272e+10,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,16.731119,2.650000,15.000000
27,Italy,19.5,0.477460,0.002177,85.600,10.100,3.568412e+11,3.663223e+09,3.059681e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,20.231270,7.020000,19.360001
28,Japan,3.7,0.301478,0.006099,87.140,10.500,2.497130e+11,2.803028e+10,2.165320e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,15.161000,2.510000,3.540000
29,"Korea, Dem. People's Rep.",7.3,0.000000,0.162713,75.119,8.856,3.048950e+10,6.771747e+08,2.523230e+10,100.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
30,Lithuania,27.8,2.953250,0.013467,80.100,14.300,2.757151e+11,6.580279e+09,2.253553e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17.027361,2.690000,7.610000
31,Malta,28.5,0.918864,0.009547,84.400,7.300,1.759970e+10,1.190127e+09,1.440067e+10,99.900002,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,17.051001,2.090000,7.760000
32,Mexico,32.8,4.477110,0.079425,77.826,5.851,2.120494e+11,7.708864e+09,1.769715e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.158890,4.390000,28.610001
33,Netherlands,20.0,0.351440,0.009194,83.200,8.700,1.605868e+11,5.597915e+09,1.285686e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,13.289240,0.000000,0.000000
34,New Zealand,31.4,0.928956,0.018237,83.400,6.610,2.626706e+10,1.030398e+09,2.057732e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,18.848000,2.490000,4.150000
35,Norway,22.5,0.422315,0.004420,84.200,7.800,3.850417e+11,3.421852e+09,2.054275e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,19.882839,2.300000,12.750000
36,Portugal,21.2,0.000000,0.010470,84.300,10.700,3.736412e+11,4.450253e+09,3.236846e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,18.819040,2.140000,4.570000
37,Poland,22.2,0.362745,0.003477,82.000,10.200,0.000000e+00,0.000000e+00,0.000000e+00,47.630955,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.796410,1.970000,10.100000
38,Russian Federation,26.9,5.326215,0.032981,77.060,12.900,5.375091e+10,1.547827e+09,4.535771e+10,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.758619,5.530000,8.390000
39,Singapore,6.3,0.259759,0.010204,85.100,4.800,1.486471e+10,1.111946e+08,0.000000e+00,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,15.921450,4.810000,0.000000
40,South Africa,39.6,0.000000,0.313375,66.654,9.599,1.180962e+11,1.442750e+10,1.015128e+11,98.099998,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.729259,0.000000,5.600000
41,Spain,22.8,0.475864,0.004869,86.300,8.800,2.122257e+11,1.199578e+10,1.725410e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,13.867560,13.170000,34.150002
42,Sweden,18.1,0.589786,0.008172,84.100,9.200,4.369997e+11,8.141285e+09,3.503814e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,18.209591,10.150000,11.860000
43,Switzerland,16.9,0.591043,0.008183,85.600,7.800,2.423131e+11,4.934779e+09,1.936451e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,4.260000,4.750000
44,Thailand,12.7,0.000000,0.052834,80.189,7.467,5.874117e+11,1.373619e+10,4.949025e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,16.311640,3.180000,5.890000
45,Turkey,39.2,1.081064,0.038059,79.816,5.390,3.759815e+11,1.135824e+08,2.730617e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.705629,1.700000,18.920000
46,Ukraine,25.7,0.000000,0.028803,76.460,14.700,5.554554e+11,7.736308e+09,4.704748e+11,100.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,17.613480,16.799999,33.470001
47,United States,37.0,2.277249,0.034195,81.100,8.493,5.066111e+11,4.145954e+10,3.880200e+11,99.820000,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.000000,6.810000,0.000000
48,United Kingdom,28.6,0.867361,0.013099,83.000,9.100,1.308910e+11,1.327174e+10,1.154703e+11,100.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,17.737129,2.490000,11.220000
49,Morocco,32.2,0.592692,0.185406,77.202,5.093,4.048421e+11,9.211179e+09,3.316214e+11,84.699997,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.909849,2.480000,11.540000

In [310]:
def normalize(df_col):
    return (df_col-df_col.min())/(df_col.max()-df_col.min())

In [320]:
moj_df_norm = moj_df.copy()

moj_df_norm['obesity'] = normalize(moj_df['Death rate']) # zastap 'nazwa_kolumny' kolumna w Twoim dataframie, a nastepnie powtorz to dla pozostalych kolumn
moj_df_norm['Lifetime, death (%)'] = normalize(moj_df['Death rate'])
moj_df_norm['Life expectancy'] = normalize(moj_df['Death rate'])
moj_df_norm['Death rate'] = normalize(moj_df['Death rate'])
moj_df_norm['GDP'] = normalize(moj_df['Death rate'])
moj_df_norm['Agriculture'] = normalize(moj_df['Death rate'])
moj_df_norm['Net income'] = normalize(moj_df['Death rate'])
moj_df_norm['Access to electricity'] = normalize(moj_df['Death rate'])
moj_df_norm['Expected  schooling'] = normalize(moj_df['Death rate'])
moj_df_norm['Unemployment with education,'] = normalize(moj_df['Death rate'])
moj_df_norm['Share of youth not in education'] = normalize(moj_df['Death rate'])

moj_df_norm.columns

Index(['Country', 'obesity', 'Intentional homicides', 'Lifetime, death (%)',
       'Life expectancy', 'Death rate', 'GDP', 'Agriculture', 'Net income',
       'Access to electricity', 'A woman in ob dangerous',
       'A woman in industrial', 'A woman  night', 'A woman a job in man',
       'A woman can trave', 'A woman a business', 'A woman  a bank account',
       'A woman rights', 'Expected  schooling', 'Unemployment with education,',
       'Share of youth not in education'],
      dtype='object')

In [321]:
moj_df_norm # znormalizowane

,Country,obesity,Intentional homicides,"Lifetime, death (%)",Life expectancy,Death rate,GDP,Agriculture,Net income,Access to electricity,...,A woman in industrial,A woman night,A woman a job in man,A woman can trave,A woman a business,A woman a bank account,A woman rights,Expected schooling,"Unemployment with education,",Share of youth not in education
0,Argentina,0.274369,0.000000,0.274369,0.274369,0.274369,0.274369,0.274369,0.274369,0.274369,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.274369,0.274369,0.274369
1,Australia,0.174757,0.656959,0.174757,0.174757,0.174757,0.174757,0.174757,0.174757,0.174757,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.174757,0.174757,0.174757
2,Austria,0.427184,0.717616,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.427184,0.427184,0.427184
3,Belgium,0.456311,0.000000,0.456311,0.456311,0.456311,0.456311,0.456311,0.456311,0.456311,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.456311,0.456311,0.456311
4,Belarus,0.757282,2.099139,0.757282,0.757282,0.757282,0.757282,0.757282,0.757282,0.757282,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.757282,0.757282,0.757282
5,Brazil,0.146699,4.053943,0.146699,0.146699,0.146699,0.146699,0.146699,0.146699,0.146699,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.146699,0.146699,0.146699
6,Canada,0.252427,0.828751,0.252427,0.252427,0.252427,0.252427,0.252427,0.252427,0.252427,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.252427,0.252427,0.252427
7,Bulgaria,1.000000,0.598682,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000
8,Chile,0.115825,0.961061,0.115825,0.115825,0.115825,0.115825,0.115825,0.115825,0.115825,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.115825,0.115825,0.115825
9,Colombia,0.063398,4.226919,0.063398,0.063398,0.063398,0.063398,0.063398,0.063398,0.063398,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.063398,0.063398,0.063398
10,China,0.217476,0.000000,0.217476,0.217476,0.217476,0.217476,0.217476,0.217476,0.217476,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.217476,0.217476,0.217476
11,Croatia,0.728155,0.915552,0.728155,0.728155,0.728155,0.728155,0.728155,0.728155,0.728155,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.728155,0.728155,0.728155
12,Czech Republic,0.524272,0.666688,0.524272,0.524272,0.524272,0.524272,0.524272,0.524272,0.524272,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.524272,0.524272,0.524272
13,Cyprus,0.202913,0.855931,0.202913,0.202913,0.202913,0.202913,0.202913,0.202913,0.202913,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.202913,0.202913,0.202913
14,Denmark,0.427184,0.801130,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.427184,0.427184,0.427184
15,"Egypt, Arab Rep.",0.108252,0.000000,0.108252,0.108252,0.108252,0.108252,0.108252,0.108252,0.108252,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.108252,0.108252,0.108252
16,Estonia,0.669903,1.286889,0.669903,0.669903,0.669903,0.669903,0.669903,0.669903,0.669903,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.669903,0.669903,0.669903
17,Finland,0.485437,0.788341,0.485437,0.485437,0.485437,0.485437,0.485437,0.485437,0.485437,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.485437,0.485437,0.485437
18,France,0.398058,1.028481,0.398058,0.398058,0.398058,0.398058,0.398058,0.398058,0.398058,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.398058,0.398058,0.398058
19,Georgia,0.795340,1.620563,0.795340,0.795340,0.795340,0.795340,0.795340,0.795340,0.795340,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.795340,0.795340,0.795340
20,Greece,0.601942,0.481106,0.601942,0.601942,0.601942,0.601942,0.601942,0.601942,0.601942,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.601942,0.601942,0.601942
21,Germany,0.611650,1.123905,0.611650,0.611650,0.611650,0.611650,0.611650,0.611650,0.611650,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.611650,0.611650,0.611650
22,Hungary,0.796117,1.602628,0.796117,0.796117,0.796117,0.796117,0.796117,0.796117,0.796117,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.796117,0.796117,0.796117
23,Iceland,0.203883,0.603992,0.203883,0.203883,0.203883,0.203883,0.203883,0.203883,0.203883,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.203883,0.203883,0.203883
24,Ireland,0.155340,0.084343,0.155340,0.155340,0.155340,0.155340,0.155340,0.155340,0.155340,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.155340,0.155340,0.155340
25,India,0.232524,2.833142,0.232524,0.232524,0.232524,0.232524,0.232524,0.232524,0.232524,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.232524,0.232524,0.232524
26,Israel,0.038835,0.563076,0.038835,0.038835,0.038835,0.038835,0.038835,0.038835,0.038835,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.038835,0.038835,0.038835
27,Italy,0.514563,0.477460,0.514563,0.514563,0.514563,0.514563,0.514563,0.514563,0.514563,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.514563,0.514563,0.514563
28,Japan,0.553398,0.301478,0.553398,0.553398,0.553398,0.553398,0.553398,0.553398,0.553398,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.553398,0.553398,0.553398
29,"Korea, Dem. People's Rep.",0.393786,0.000000,0.393786,0.393786,0.393786,0.393786,0.393786,0.393786,0.393786,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.393786,0.393786,0.393786
30,Lithuania,0.922330,2.953250,0.922330,0.922330,0.922330,0.922330,0.922330,0.922330,0.922330,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.922330,0.922330,0.922330
31,Malta,0.242718,0.918864,0.242718,0.242718,0.242718,0.242718,0.242718,0.242718,0.242718,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.242718,0.242718,0.242718
32,Mexico,0.102039,4.477110,0.102039,0.102039,0.102039,0.102039,0.102039,0.102039,0.102039,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.102039,0.102039,0.102039
33,Netherlands,0.378641,0.351440,0.378641,0.378641,0.378641,0.378641,0.378641,0.378641,0.378641,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.378641,0.378641,0.378641
34,New Zealand,0.175728,0.928956,0.175728,0.175728,0.175728,0.175728,0.175728,0.175728,0.175728,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.175728,0.175728,0.175728
35,Norway,0.291262,0.422315,0.291262,0.291262,0.291262,0.291262,0.291262,0.291262,0.291262,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.291262,0.291262,0.291262
36,Portugal,0.572816,0.000000,0.572816,0.572816,0.572816,0.572816,0.572816,0.572816,0.572816,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.572816,0.572816,0.572816
37,Poland,0.524272,0.362745,0.524272,0.524272,0.524272,0.524272,0.524272,0.524272,0.524272,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.524272,0.524272,0.524272
38,Russian Federation,0.786408,5.326215,0.786408,0.786408,0.786408,0.786408,0.786408,0.786408,0.786408,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.786408,0.786408,0.786408
39,Singapore,0.000000,0.259759,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000
40,South Africa,0.465922,0.000000,0.465922,0.465922,0.465922,0.465922,0.465922,0.465922,0.465922,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.465922,0.465922,0.465922
41,Spain,0.388350,0.475864,0.388350,0.388350,0.388350,0.388350,0.388350,0.388350,0.388350,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.388350,0.388350,0.388350
42,Sweden,0.427184,0.589786,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.427184,0.427184,0.427184
43,Switzerland,0.291262,0.591043,0.291262,0.291262,0.291262,0.291262,0.291262,0.291262,0.291262,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.291262,0.291262,0.291262
44,Thailand,0.258932,0.000000,0.258932,0.258932,0.258932,0.258932,0.258932,0.258932,0.258932,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.258932,0.258932,0.258932
45,Turkey,0.057282,1.081064,0.057282,0.057282,0.057282,0.057282,0.057282,0.057282,0.057282,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.057282,0.057282,0.057282
46,Ukraine,0.961165,0.000000,0.961165,0.961165,0.961165,0.961165,0.961165,0.961165,0.961165,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.961165,0.961165,0.961165
47,United States,0.358544,2.277249,0.358544,0.358544,0.358544,0.358544,0.358544,0.358544,0.358544,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.358544,0.358544,0.358544
48,United Kingdom,0.417476,0.867361,0.417476,0.417476,0.417476,0.417476,0.417476,0.417476,0.417476,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.417476,0.417476,0.417476
49,Morocco,0.028447,0.592692,0.028447,0.028447,0.028447,0.028447,0.028447,0.028447,0.028447,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.028447,0.028447,0.028447

In [322]:
moj_df_norm.describe()

,obesity,Intentional homicides,"Lifetime, death (%)",Life expectancy,Death rate,GDP,Agriculture,Net income,Access to electricity,A woman in ob dangerous,A woman in industrial,A woman night,A woman a job in man,A woman can trave,A woman a business,A woman a bank account,A woman rights,Expected schooling,"Unemployment with education,",Share of youth not in education
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,0.399561,1.053070,0.399561,0.399561,0.399561,0.399561,0.399561,0.399561,0.399561,0.800000,0.680000,0.920000,0.960000,0.960000,0.980000,0.980000,0.840000,0.399561,0.399561,0.399561
std,0.259692,1.242252,0.259692,0.259692,0.259692,0.259692,0.259692,0.259692,0.259692,0.404061,0.471212,0.274048,0.197949,0.197949,0.141421,0.141421,0.370328,0.259692,0.259692,0.259692
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.203155,0.354266,0.203155,0.203155,0.203155,0.203155,0.203155,0.203155,0.203155,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.203155,0.203155,0.203155
50%,0.391068,0.661823,0.391068,0.391068,0.391068,0.391068,0.391068,0.391068,0.391068,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.391068,0.391068,0.391068
75%,0.546117,1.067918,0.546117,0.546117,0.546117,0.546117,0.546117,0.546117,0.546117,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.546117,0.546117,0.546117
max,1.000000,5.326215,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [323]:
liczba_kolumn = moj_df_norm.shape[1] # zapiszmy liczbe interesujacych nas kolumn

moj_df_norm_do_liczenia = moj_df_norm.copy()

moj_df_norm_do_liczenia.drop('Country', axis=1, inplace=True) # zapiszmy tu kolumny, na ktorych bedziemy liczyc srednia (czyli bez nazw krajow)

moj_df_norm_do_liczenia

,obesity,Intentional homicides,"Lifetime, death (%)",Life expectancy,Death rate,GDP,Agriculture,Net income,Access to electricity,A woman in ob dangerous,A woman in industrial,A woman night,A woman a job in man,A woman can trave,A woman a business,A woman a bank account,A woman rights,Expected schooling,"Unemployment with education,",Share of youth not in education
0,0.274369,0.000000,0.274369,0.274369,0.274369,0.274369,0.274369,0.274369,0.274369,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.274369,0.274369,0.274369
1,0.174757,0.656959,0.174757,0.174757,0.174757,0.174757,0.174757,0.174757,0.174757,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.174757,0.174757,0.174757
2,0.427184,0.717616,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.427184,0.427184,0.427184
3,0.456311,0.000000,0.456311,0.456311,0.456311,0.456311,0.456311,0.456311,0.456311,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.456311,0.456311,0.456311
4,0.757282,2.099139,0.757282,0.757282,0.757282,0.757282,0.757282,0.757282,0.757282,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.757282,0.757282,0.757282
5,0.146699,4.053943,0.146699,0.146699,0.146699,0.146699,0.146699,0.146699,0.146699,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.146699,0.146699,0.146699
6,0.252427,0.828751,0.252427,0.252427,0.252427,0.252427,0.252427,0.252427,0.252427,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.252427,0.252427,0.252427
7,1.000000,0.598682,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000
8,0.115825,0.961061,0.115825,0.115825,0.115825,0.115825,0.115825,0.115825,0.115825,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.115825,0.115825,0.115825
9,0.063398,4.226919,0.063398,0.063398,0.063398,0.063398,0.063398,0.063398,0.063398,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.063398,0.063398,0.063398
10,0.217476,0.000000,0.217476,0.217476,0.217476,0.217476,0.217476,0.217476,0.217476,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.217476,0.217476,0.217476
11,0.728155,0.915552,0.728155,0.728155,0.728155,0.728155,0.728155,0.728155,0.728155,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.728155,0.728155,0.728155
12,0.524272,0.666688,0.524272,0.524272,0.524272,0.524272,0.524272,0.524272,0.524272,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.524272,0.524272,0.524272
13,0.202913,0.855931,0.202913,0.202913,0.202913,0.202913,0.202913,0.202913,0.202913,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.202913,0.202913,0.202913
14,0.427184,0.801130,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.427184,0.427184,0.427184
15,0.108252,0.000000,0.108252,0.108252,0.108252,0.108252,0.108252,0.108252,0.108252,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.108252,0.108252,0.108252
16,0.669903,1.286889,0.669903,0.669903,0.669903,0.669903,0.669903,0.669903,0.669903,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.669903,0.669903,0.669903
17,0.485437,0.788341,0.485437,0.485437,0.485437,0.485437,0.485437,0.485437,0.485437,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.485437,0.485437,0.485437
18,0.398058,1.028481,0.398058,0.398058,0.398058,0.398058,0.398058,0.398058,0.398058,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.398058,0.398058,0.398058
19,0.795340,1.620563,0.795340,0.795340,0.795340,0.795340,0.795340,0.795340,0.795340,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.795340,0.795340,0.795340
20,0.601942,0.481106,0.601942,0.601942,0.601942,0.601942,0.601942,0.601942,0.601942,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.601942,0.601942,0.601942
21,0.611650,1.123905,0.611650,0.611650,0.611650,0.611650,0.611650,0.611650,0.611650,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.611650,0.611650,0.611650
22,0.796117,1.602628,0.796117,0.796117,0.796117,0.796117,0.796117,0.796117,0.796117,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.796117,0.796117,0.796117
23,0.203883,0.603992,0.203883,0.203883,0.203883,0.203883,0.203883,0.203883,0.203883,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.203883,0.203883,0.203883
24,0.155340,0.084343,0.155340,0.155340,0.155340,0.155340,0.155340,0.155340,0.155340,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.155340,0.155340,0.155340
25,0.232524,2.833142,0.232524,0.232524,0.232524,0.232524,0.232524,0.232524,0.232524,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.232524,0.232524,0.232524
26,0.038835,0.563076,0.038835,0.038835,0.038835,0.038835,0.038835,0.038835,0.038835,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.038835,0.038835,0.038835
27,0.514563,0.477460,0.514563,0.514563,0.514563,0.514563,0.514563,0.514563,0.514563,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.514563,0.514563,0.514563
28,0.553398,0.301478,0.553398,0.553398,0.553398,0.553398,0.553398,0.553398,0.553398,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.553398,0.553398,0.553398
29,0.393786,0.000000,0.393786,0.393786,0.393786,0.393786,0.393786,0.393786,0.393786,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.393786,0.393786,0.393786
30,0.922330,2.953250,0.922330,0.922330,0.922330,0.922330,0.922330,0.922330,0.922330,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.922330,0.922330,0.922330
31,0.242718,0.918864,0.242718,0.242718,0.242718,0.242718,0.242718,0.242718,0.242718,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.242718,0.242718,0.242718
32,0.102039,4.477110,0.102039,0.102039,0.102039,0.102039,0.102039,0.102039,0.102039,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.102039,0.102039,0.102039
33,0.378641,0.351440,0.378641,0.378641,0.378641,0.378641,0.378641,0.378641,0.378641,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.378641,0.378641,0.378641
34,0.175728,0.928956,0.175728,0.175728,0.175728,0.175728,0.175728,0.175728,0.175728,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.175728,0.175728,0.175728
35,0.291262,0.422315,0.291262,0.291262,0.291262,0.291262,0.291262,0.291262,0.291262,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.291262,0.291262,0.291262
36,0.572816,0.000000,0.572816,0.572816,0.572816,0.572816,0.572816,0.572816,0.572816,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.572816,0.572816,0.572816
37,0.524272,0.362745,0.524272,0.524272,0.524272,0.524272,0.524272,0.524272,0.524272,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.524272,0.524272,0.524272
38,0.786408,5.326215,0.786408,0.786408,0.786408,0.786408,0.786408,0.786408,0.786408,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.786408,0.786408,0.786408
39,0.000000,0.259759,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000
40,0.465922,0.000000,0.465922,0.465922,0.465922,0.465922,0.465922,0.465922,0.465922,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.465922,0.465922,0.465922
41,0.388350,0.475864,0.388350,0.388350,0.388350,0.388350,0.388350,0.388350,0.388350,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.388350,0.388350,0.388350
42,0.427184,0.589786,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,0.427184,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.427184,0.427184,0.427184
43,0.291262,0.591043,0.291262,0.291262,0.291262,0.291262,0.291262,0.291262,0.291262,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.291262,0.291262,0.291262
44,0.258932,0.000000,0.258932,0.258932,0.258932,0.258932,0.258932,0.258932,0.258932,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.258932,0.258932,0.258932
45,0.057282,1.081064,0.057282,0.057282,0.057282,0.057282,0.057282,0.057282,0.057282,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.057282,0.057282,0.057282
46,0.961165,0.000000,0.961165,0.961165,0.961165,0.961165,0.961165,0.961165,0.961165,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.961165,0.961165,0.961165
47,0.358544,2.277249,0.358544,0.358544,0.358544,0.358544,0.358544,0.358544,0.358544,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.358544,0.358544,0.358544
48,0.417476,0.867361,0.417476,0.417476,0.417476,0.417476,0.417476,0.417476,0.417476,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.417476,0.417476,0.417476
49,0.028447,0.592692,0.028447,0.028447,0.028447,0.028447,0.028447,0.028447,0.028447,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.028447,0.028447,0.028447

In [324]:
def srednia_wazona(dataframe_do_liczenia, wagi):
    licznik = (dataframe_do_liczenia*wagi).sum(axis=1)
    mianownik = sum(wagi)
    return licznik/mianownik

In [325]:
moje_wagi = [-0.04, -0.105, -0.05, 0.05, -0.01, 0.015, 0.015, 0.022, 0.15, 0.03, 0.01, 0.23, 0.2, 0.148, 0.04, 0.04, 0.44, 0.03, -0.015, -0.2, ] # wagi mozemy zapisac wewnatrz nawiasow kwadratowych - tworzymy w ten sposob liste, o kt√≥rej dowiecie siƒô wiƒôcej w dalszej czesci kursu
sum(moje_wagi)

1.0000000000000002

In [ ]:
(moj_df_norm_do_liczenia,)
moj_df_norm['srednia_wazona'] = srednia_wazona(moj_df_norm_do_liczenia, moje_wagi)
moj_df_norm

In [ ]:
moj_df_norm_uszeregowane = moj_df_norm.sort_values('srednia_wazona', ascending=False)
moj_df_norm_uszeregowane

In [ ]:
moj_df_norm_uszeregowane.iloc[:,:] # pierwsze 3 wiersze, wszystkie kolumny

In [ ]:
moj_df_norm.to_excel('moj_dataframe_norm.xlsx') # 'moj_dataframe_norm.xlsx' mozecie podmienic na dowolna inna nazwe, ktora chcecie nazwac swoj plik formatu excel